Repository ckb-cell/rgbpp-sdk, pull requests merged in 2024-05, with the labels that each got.

#158 docs: update README related to assets-api
  README.md
  packages/service/README.md
Labels: documentation

#168 fix(ckb/btc): Check rgbpp capacity for change and paymaster cell
  packages/btc/src/api/sendRgbppUtxos.ts
  packages/ckb/src/rgbpp/btc-jump-ckb.ts
  packages/ckb/src/rgbpp/btc-transfer.ts
  packages/ckb/src/utils/ckb-tx.spec.ts
  packages/ckb/src/utils/ckb-tx.ts
  packages/ckb/src/utils/rgbpp.spec.ts
  packages/ckb/src/utils/rgbpp.ts
Labels: P-Medium

#185 fix(rgbpp-sdk/ckb): Update RGB++ inputs length of Spore creation TX
  packages/ckb/src/spore/spore.ts
Labels: P-High

#169 test: Create integration tests for xUDT workflow
  .github/workflows/integration-test.yaml
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  tests/rgbpp/env.ts
  tests/rgbpp/package.json
  tests/rgbpp/shared/prepare-utxo.ts
  tests/rgbpp/shared/utils.ts
  tests/rgbpp/testnet/.gitkeep
  tests/rgbpp/tsconfig.json
  tests/rgbpp/xudt/1-ckb-leap-btc.ts
  tests/rgbpp/xudt/2-btc-transfer.ts
  tests/rgbpp/xudt/3-btc-leap-ckb.ts
  tests/rgbpp/xudt/xudt-on-ckb/1-issue-xudt.ts
Labels: P-Medium

#199 feat(btc|examples): add needPaymaster option in the sendRgbppUtxos() API
  .changeset/warm-tomatoes-worry.md
  examples/rgbpp/spore/4-transfer-spore.ts
  examples/rgbpp/spore/5-leap-spore-to-ckb.ts
  examples/rgbpp/spore/launch/2-create-cluster.ts
  examples/rgbpp/spore/launch/3-create-spores.ts
  examples/rgbpp/spore/local/4-transfer-spore.ts
  examples/rgbpp/spore/local/5-leap-spore-to-ckb.ts
  examples/rgbpp/tsconfig.json
  examples/rgbpp/xudt/launch/2-launch-rgbpp.ts
  examples/rgbpp/xudt/launch/3-distribute-rgbpp.ts
  packages/btc/src/api/sendRgbppUtxos.ts
Labels: P-Medium
